---
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.4.1
jobs:
  deploy_stage:
    docker: # run the steps with Docker
      - image: cimg/php:7.4.22
    steps:
      - checkout
      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs rsync grsync
      - run: sudo npm install --global yarn 
      - run:
          name: install composer version 
          command: |
            sudo composer self-update 1.10.22
      - run:
          name: install dependencies
          command: |
            yarn install
      - run:
          name: build site in dev mode
          command: |
            yarn run build:dev
      - run:
          name: Deploy over SSH
          command: |
            rsync -e 'ssh -p 12345 -o StrictHostKeyChecking=accept-new' -rtDvzhO --exclude 'node_modules' . $SSH_USER@$SSH_HOST_STAGE:$SSH_PATH

  deploy_prod:
    docker: # run the steps with Docker
      - image: cimg/php:7.4.22
    steps:
      - checkout
      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs rsync grsync
      - run: sudo npm install --global yarn 
      - run:
          name: install composer version 
          command: |
            sudo composer self-update 1.10.22
      - run:
          name: install dependencies
          command: |
            yarn install
      - run:
          name: build site in dev mode
          command: |
            yarn run build:dev
      - run:
          name: Deploy over SSH
          command: |
            rsync -e 'ssh -p 12345 -o StrictHostKeyChecking=accept-new' -rtDvzhO --exclude 'node_modules' . $SSH_USER@$SSH_HOST_PROD:$SSH_PATH

workflows:
  version: 2
  pipeline:
    jobs:
      - deploy_stage:
          filters:
            branches:
              only: staging
      - deploy_prod:
          filters:
            branches:
              only: main
